name: Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]
    runs-on: ${{ matrix.platform }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add steps to install dependencies
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Example for installing Rust
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable

      # Add steps to compile your Tauri app
      - name: Install Tauri CLI
        run: npm install -g @tauri-apps/cli

      - name: Install app dependencies
        run: npm install

      # Update the bundle identifier in tauri.conf.json
      - name: Update bundle identifier
        run: sed -i 's/com.tauri.dev/your.unique.bundle.identifier/' tauri.conf.json

      - name: Build Tauri app
        run: tauri build
